name: 'Terraform apply'
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: The environment to deploy against.
        type: string
        default: intg
permissions:
  id-token: write
  contents: write
jobs:
  setup:
    uses: nationalarchives/dr2-github-actions/.github/workflows/set_terraform_var_names.yml@main
    with:
      project: tdr
      environment: ${{ github.event.inputs.environment }}
  apply:
    uses: ./.github/workflows/terraform_apply.yml
    needs: setup
    with:
      repo-name: tdr-aws-accounts
      environment: ${{ github.event.inputs.environment }}
      project: tdr
    secrets:
      WORKFLOW_TOKEN: ${{ secrets[needs.setup.outputs.workflow-token] }}
      ACCOUNT_NUMBER: ${{ secrets[needs.setup.outputs.account-number] }}
      SLACK_WEBHOOK: ${{ secrets[needs.setup.outputs.slack-webhook] }}
      TERRAFORM_ROLE: ${{ secrets[needs.setup.outputs.terraform-role] }}
