name: 'Terraform apply'
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: The environment to deploy against.
        type: string
        default: intg
      project:
        required: true
        description: The project to run this for
        type: choice
        options:
          - tdr
          - dr2
permissions:
  id-token: write
  contents: write
jobs:
  setup:
    uses: nationalarchives/dr2-github-actions/.github/workflows/set_terraform_var_names.yml@create-generic-apply-job
    with:
      project: ${{ github.event.inputs.project }}
      environment: ${{ github.event.inputs.environment }}
  apply:
    uses: nationalarchives/dr2-github-actions/.github/workflows/terraform_apply.yml@create-generic-apply-job
    needs: setup
    with:
      repo-name: tna-custodian
      environment: ${{ github.event.inputs.environment }}
      working-directory: terraform
      project: ${{ github.event.inputs.project }}
    secrets:
      WORKFLOW_TOKEN: ${{ secrets[needs.setup.outputs.workflow-token] }}
      ACCOUNT_NUMBER: ${{ secrets[needs.setup.outputs.account-number] }}
      SLACK_WEBHOOK: ${{ secrets[needs.setup.outputs.slack-webhook] }}
      TERRAFORM_ROLE: ${{ secrets[needs.setup.outputs.terraform-role] }}
      STATE_BUCKET: ${{ secrets[needs.setup.outputs.state-bucket] }}
      DYNAMO_TABLE: ${{ secrets[needs.setup.outputs.dynamo-table] }}
  delete-vpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets[needs.setup.outputs.workflow-token] }}
      - name: Configure AWS credentials for Lambda
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets[needs.setup.outputs.terraform-role] }}
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - run: |
          pip install boto3 
          python ./python/delete-default-vpcs.py --account_number=${{ secrets[needs.setup.outputs.account-number] }} --stage=${{ github.event.inputs.environment }} --deployment_type=github
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        with:
          message: "${{ inputs.environment }} default VPCs deleted in all regions"
          slack-url: ${{ secrets[needs.setup.outputs.slack-webhook] }}
