name: 'Terraform check'
on:
  pull_request:
permissions:
  id-token: write
  contents: write
jobs:
  check:
    uses: nationalarchives/tdr-github-actions/.github/workflows/terraform_check.yml@main
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.TDR_MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      STATE_BUCKET: ${{ TDR_MGMT_STATE_BUCKET }}
      DYNAMO_TABLE: ${{ TDR_MGMT_DYNAMO_TABLE }}
