name: 'Terraform check'
on:
  pull_request:
permissions:
  id-token: write
  contents: write
jobs:
  check:
    uses: ./.github/workflows/terraform_check.yml
    secrets:
      TERRAFORM_ROLE: ${{ secrets.DR2_INTG_TERRAFORM_ROLE }}
      WORKFLOW_TOKEN: ${{ secrets.DR2_WORKFLOW_PAT }}
      
