name: Run git secrets and tests
on:
  workflow_call:
    inputs:
      use-workspace:
        type: boolean
        required: false
        default: true
      working-directory:
        type: string
        required: false
        default: .
    secrets:
      WORKFLOW_TOKEN:
        required: true
      TERRAFORM_ROLE:
        required: true
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          submodules: recursive
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Configure AWS credentials for Lambda
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a
        with:
          role-to-assume: ${{ secrets.TERRAFORM_ROLE }}
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - uses: nationalarchives/dr2-github-actions/.github/actions/run-git-secrets@917201e254f112ff041b952dae76ef767cae7378
      - uses: nationalarchives/dr2-github-actions/.github/actions/slack-send@917201e254f112ff041b952dae76ef767cae7378
        if: failure()
        with:
          message: ":warning: Secrets found in repository: *${{ inputs.repo-name }}* @channel"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - uses: hashicorp/setup-terraform@1428cf060329a44e3a0ee695a66e5b3f2409ec85
        with:
          terraform_version: 1.12.2
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check --recursive
